name: Build ZIP file
on:
  push:
  pull_request:

jobs:
  build_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get module version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'module.json'
            prop_path: 'version'

      - name: Set version in module.prop
        run: |
          sed -i -e "s/\bVER\b/${{steps.version.outputs.prop}}/g" $GITHUB_WORKSPACE/module.prop
          VERCODE=$(grep -Eo '[0-9][0-9][0-9]' $GITHUB_WORKSPACE/module.json)
          sed -i -e "s/\bVERCODE\b/$VERCODE/g" $GITHUB_WORKSPACE/module.prop
      
      - name: Create ZIP archive
        run: |
          zip -r ${{ github.event.repository.name }}.zip ./* -x module.json

      - name: Upload modules to release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{steps.version.outputs.prop}}
          name: ${{steps.version.outputs.prop}}
          files: ${{ github.event.repository.name }}.zip
          gzip: false
          draft: false
          prerelease: false
          allow_override: true

      - name: Cleanup module zip
        run:  |
          rm ${{ github.event.repository.name }}.zip

      
    